id: I399EBFBE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T09:05:04+00:00'
last_modified: '2022-06-16T05:32:38.482348+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG11865
  title: འབྲི་གུང་བཀའ་བརྒྱུད་ཀྱི་འདོན་ཆོག་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    2B6F:
      image_group_id: I1KG22626
      title: ''
      total_pages: 574
      order: 1
      base_file: 2B6F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
