id: I399EBFBE
legacy_id: P003026
ocr_import_info:
  bdrc_scan_id: W1KG11865
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T09:01:09'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:09:32.035768+00:00'
last_modified: 2022-08-31 11:10:11.089127
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG11865
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG11865
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འབྲི་གུང་བཀའ་བརྒྱུད་ཀྱི་འདོན་ཆོག་སྐོར།
statistics:
  ocr_word_mean_confidence_index: 0.8451265324013274
  ocr_word_median_confidence_index: 0.9300000071525574
quality: null
bases:
  I1KG22626:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22626
      total_pages: 574
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG22626.txt
    statistics:
      ocr_word_median_confidence_index: 0.9300000071525574
      ocr_word_mean_confidence_index: 0.8547124470179179
    legacy_id: v001
  I1KG22627:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22627
      total_pages: 562
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG22627.txt
    statistics:
      ocr_word_median_confidence_index: 0.9300000071525574
      ocr_word_mean_confidence_index: 0.839444120211724
    legacy_id: v002
  I1KG22628:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22628
      total_pages: 600
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG22628.txt
    statistics:
      ocr_word_median_confidence_index: 0.9200000166893005
      ocr_word_mean_confidence_index: 0.8412177400992779
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
